/* Generated by Yosys 0.66 (git sha1 7f8fdfd8d7bc08c749a2a969388d3425d4f369d5, clang++ 21.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "../rtl/alu.v:5.1-70.10" *)
module alu(a, b, opcode, result, carry_out, zero_flag);
  (* src = "../rtl/alu.v:6.18-6.19" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "../rtl/alu.v:7.18-7.19" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "../rtl/alu.v:8.18-8.24" *)
  input [2:0] opcode;
  wire [2:0] opcode;
  (* src = "../rtl/alu.v:9.22-9.28" *)
  output [3:0] result;
  wire [3:0] result;
  (* src = "../rtl/alu.v:10.22-10.31" *)
  output carry_out;
  wire carry_out;
  (* src = "../rtl/alu.v:11.22-11.31" *)
  output zero_flag;
  wire zero_flag;
  (* src = "../rtl/alu.v:35.19-35.21" *)
  wire _000_;
  (* src = "../rtl/alu.v:35.19-35.21" *)
  wire _001_;
  (* src = "../rtl/alu.v:35.19-35.21" *)
  wire _002_;
  (* src = "../rtl/alu.v:35.19-35.21" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  (* src = "../rtl/alu.v:25.16-25.25" *)
  wire add_carry;
  (* src = "../rtl/alu.v:24.16-24.26" *)
  wire [3:0] add_result;
  (* src = "../rtl/alu.v:25.28-25.38" *)
  wire sub_borrow;
  (* src = "../rtl/alu.v:24.28-24.38" *)
  wire [3:0] sub_result;
  assign _002_ = ~b[2];
  assign _001_ = ~b[1];
  assign _000_ = ~b[0];
  assign _003_ = ~b[3];
  assign _023_ = b[2] | a[2];
  assign _024_ = ~(opcode[0] & opcode[1]);
  assign _025_ = opcode[2] | _024_;
  assign _026_ = ~(b[2] & a[2]);
  assign _027_ = ~(opcode[0] | opcode[1]);
  assign _028_ = opcode[2] & _027_;
  assign _029_ = ~(_026_ & _028_);
  assign _030_ = ~(_025_ & _029_);
  assign _031_ = ~(_023_ & _030_);
  assign _032_ = opcode[0] & ~(opcode[1]);
  assign _033_ = ~(opcode[2] & _032_);
  assign _034_ = a[2] | _033_;
  assign _035_ = opcode[2] & ~(_024_);
  assign _036_ = ~(a[3] & _035_);
  assign _037_ = _034_ & _036_;
  assign _038_ = opcode[1] & ~(opcode[0]);
  assign _039_ = _038_ & ~(opcode[2]);
  assign _040_ = _026_ | ~(_039_);
  assign _041_ = _027_ & ~(opcode[2]);
  assign _042_ = ~(add_result[2] & _041_);
  assign _043_ = _040_ & _042_;
  assign _044_ = opcode[2] & _038_;
  assign _045_ = ~(a[1] & _044_);
  assign _046_ = _032_ & ~(opcode[2]);
  assign _047_ = ~(sub_result[2] & _046_);
  assign _048_ = _045_ & _047_;
  assign _049_ = _043_ & _048_;
  assign _050_ = _037_ & _049_;
  assign result[2] = ~(_031_ & _050_);
  assign _051_ = b[1] | a[1];
  assign _052_ = b[1] & a[1];
  assign _053_ = _052_ | ~(_028_);
  assign _054_ = ~(_025_ & _053_);
  assign _055_ = ~(_051_ & _054_);
  assign _056_ = ~(sub_result[1] & _046_);
  assign _057_ = ~(add_result[1] & _041_);
  assign _058_ = _056_ & _057_;
  assign _059_ = a[1] | _033_;
  assign _060_ = ~(a[2] & _035_);
  assign _061_ = _059_ & _060_;
  assign _062_ = ~(a[0] & _044_);
  assign _063_ = ~(_039_ & _052_);
  assign _064_ = _062_ & _063_;
  assign _065_ = _061_ & _064_;
  assign _066_ = _058_ & _065_;
  assign result[1] = ~(_055_ & _066_);
  assign _067_ = b[0] | a[0];
  assign _068_ = b[0] & a[0];
  assign _069_ = _068_ | ~(_028_);
  assign _070_ = ~(_025_ & _069_);
  assign _071_ = ~(_067_ & _070_);
  assign _072_ = ~(sub_result[0] & _046_);
  assign _073_ = ~(add_result[0] & _041_);
  assign _074_ = _072_ & _073_;
  assign _075_ = a[0] | _033_;
  assign _076_ = ~(a[1] & _035_);
  assign _077_ = ~(_039_ & _068_);
  assign _078_ = _076_ & _077_;
  assign _079_ = _075_ & _078_;
  assign _080_ = _074_ & _079_;
  assign result[0] = ~(_071_ & _080_);
  assign _081_ = b[3] | a[3];
  assign _082_ = b[3] & a[3];
  assign _083_ = _082_ | ~(_028_);
  assign _004_ = ~(_025_ & _083_);
  assign _005_ = ~(_081_ & _004_);
  assign _006_ = ~(_039_ & _082_);
  assign _007_ = ~(sub_result[3] & _046_);
  assign _008_ = _006_ & _007_;
  assign _009_ = ~(a[2] & _044_);
  assign _010_ = a[3] | _033_;
  assign _011_ = ~(add_result[3] & _041_);
  assign _012_ = _010_ & _011_;
  assign _013_ = _009_ & _012_;
  assign _014_ = _008_ & _013_;
  assign result[3] = ~(_005_ & _014_);
  assign _015_ = ~(add_carry & _041_);
  assign _016_ = ~(a[0] & _035_);
  assign _017_ = _015_ & _016_;
  assign _018_ = ~(a[3] & _044_);
  assign _019_ = ~(sub_borrow & _046_);
  assign _020_ = _018_ & _019_;
  assign carry_out = ~(_017_ & _020_);
  assign _021_ = ~(result[2] | result[1]);
  assign _022_ = ~(result[0] | result[3]);
  assign zero_flag = _021_ & _022_;
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/alu.v:28.18-31.6" *)
  ripple_adder ADDER (
    .a(a),
    .b(b),
    .cin(1'h0),
    .cout(add_carry),
    .sum(add_result)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/alu.v:34.18-37.6" *)
  ripple_adder SUBTRACTOR (
    .a(a),
    .b({ _003_, _002_, _001_, _000_ }),
    .cin(1'h1),
    .cout(sub_borrow),
    .sum(sub_result)
  );
endmodule

(* src = "../rtl/full_adder.v:4.1-14.10" *)
module full_adder(a, b, cin, sum, cout);
  (* src = "../rtl/full_adder.v:5.12-5.13" *)
  input a;
  wire a;
  (* src = "../rtl/full_adder.v:6.12-6.13" *)
  input b;
  wire b;
  (* src = "../rtl/full_adder.v:7.12-7.15" *)
  input cin;
  wire cin;
  (* src = "../rtl/full_adder.v:8.12-8.15" *)
  output sum;
  wire sum;
  (* src = "../rtl/full_adder.v:9.12-9.16" *)
  output cout;
  wire cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  assign _03_ = cin | b;
  assign _04_ = cin & b;
  assign _05_ = a | _04_;
  assign cout = _03_ & _05_;
  assign _00_ = ~(a & _04_);
  assign _01_ = a | _03_;
  assign _02_ = ~(cout & _00_);
  assign sum = _01_ & _02_;
endmodule

(* src = "../rtl/ripple_adder.v:4.1-18.10" *)
module ripple_adder(a, b, cin, sum, cout);
  (* src = "../rtl/ripple_adder.v:5.18-5.19" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "../rtl/ripple_adder.v:6.18-6.19" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "../rtl/ripple_adder.v:7.18-7.21" *)
  input cin;
  wire cin;
  (* src = "../rtl/ripple_adder.v:8.18-8.21" *)
  output [3:0] sum;
  wire [3:0] sum;
  (* src = "../rtl/ripple_adder.v:9.18-9.22" *)
  output cout;
  wire cout;
  (* src = "../rtl/ripple_adder.v:11.10-11.12" *)
  wire c1;
  (* src = "../rtl/ripple_adder.v:11.14-11.16" *)
  wire c2;
  (* src = "../rtl/ripple_adder.v:11.18-11.20" *)
  wire c3;
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/ripple_adder.v:13.16-13.77" *)
  full_adder FA0 (
    .a(a[0]),
    .b(b[0]),
    .cin(cin),
    .cout(c1),
    .sum(sum[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/ripple_adder.v:14.16-14.77" *)
  full_adder FA1 (
    .a(a[1]),
    .b(b[1]),
    .cin(c1),
    .cout(c2),
    .sum(sum[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/ripple_adder.v:15.16-15.77" *)
  full_adder FA2 (
    .a(a[2]),
    .b(b[2]),
    .cin(c2),
    .cout(c3),
    .sum(sum[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/ripple_adder.v:16.16-16.79" *)
  full_adder FA3 (
    .a(a[3]),
    .b(b[3]),
    .cin(c3),
    .cout(cout),
    .sum(sum[3])
  );
endmodule
